mysql:
  image: mysql
  container_name: mysql-shared-budget
  environment:
    MYSQL_ROOT_PASSWORD: "root-password"
    MYSQL_DATABASE: "budget"
    MYSQL_USER: "budget"
    MYSQL_PASSWORD: "budget-password"