mysql:
  image: mysql
  container_name: mysql-shared-budget
  environment:
    MYSQL_ROOT_PASSWORD: "root-password"
    MYSQL_DATABASE: "budget"
    MYSQL_USER: "budget"
    MYSQL_PASSWORD: "budget-password"
webapp:
  image: php-shared-budget
  container_name: php-shared-budget
  links:
    - mysql
  ports:
    - "80:80"
  volumes:
    - ../:/var/budget
